verbose: false
use-conda: true
cores: all
cache: false
reason: true
use-singularity: true
singularity-args: "--bind $PWD/../data,$CUDA_INSTALL_ROOT,$CUDNN_INSTALL_ROOT:/cudnn,$PWD/../data/tmp:/tmp --nv --containall"
config:
  - deps=false
  - workspace=12000
  - numgpus=0
  - mariancmake=""
  # (optional) override available GPU ids, example gpus=0 2 5 6
  - gpus=""
