cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 8
restart-times: 0
immediate-submit: false
verbose: false
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
use-singularity: false
use-conda: false
default-resources: "mem_mb=60000"
resources: gpu=2
cores: 32
cache: false
reason: true
# if CPU nodes don't have access to cuda dirs, use
# export CUDA_DIR=$(CUDA_DIR); $(SNAKEMAKE) ...
# singularity-args: "--bind $(SHARED_ROOT),/tmp --nv --containall"
singularity-args: "--bind $PWD/../data,$CUDA_INSTALL_ROOT,$CUDNN_INSTALL_ROOT:/cudnn,$PWD/../data/tmp:/tmp --nv --containall"
config:
  - deps=false
  - workspace=30000
  - numgpus=2
  - mariancmake=""
  - gpus=""
