verbose: false
use-conda: false
resources: gpu=0
cores: 1
cache: false
reason: true
config:
  # install dependencies on a local machine
  - deps=true
  # how much memory Marian reserves on a GPU
  - workspace=2000
  # a number of GPUs you want to use
  - numgpus=0
  - mariancmake=""
  # (optional) override available GPU ids, example gpus=0 2 5 6
  - gpus=""
