cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 6
restart-times: 0
immediate-submit: false
verbose: true
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
default-resources: "mem_mb=16000"
use-singularity: false
use-conda: false
cores: 128
#cache: false
reason: true

singularity-args: "--bind /scratch/project_462000447/members/niemine1/rat/data,/tmp/$USER:/tmp --rocm --containall"
config:
  - deps=false
    #- root=/pfs/lustrep1/scratch/project_462000088/members/niemine1/data
    #- rocm=/opt/rocm
  - workspace=40000
  - numgpus=4
  - mariancmake=""
  - gpus="0 1 2 3"
  - marianversion="lumi-marian"
