# CSC Puhti
single-gpu-partition: small-g
multi-gpu-partition: standard-g
partialnode-cpu-partition: small
fullnode-cpu-partition: standard 
cpu-account: project_462000447
gpu-account: project_462000447
time-limit: "48:00:00"
