cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 16
restart-times: 0
immediate-submit: false
verbose: false
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
default-resources: ["mem_mb=128000","disk_mb=128000"]
use-singularity: true
use-conda: true
resources: gpu=16
cores: 32 #64
#cache: false
reason: true

singularity-args: "--bind /scratch/project_462000447/members/degibert/ftt,/scratch/project_462000447/members/degibert/ftt/tmp:/tmp,/usr/share/libdrm --rocm --containall"
config:
  - deps=false
  - root="/scratch/project_462000447/members/degibert/ftt"
  - rocm=/opt/rocm
  - workspace=40000
  - numgpus=8
  - mariancmake=""
  - gpus=""
  - marianversion="lumi-marian"

