name: bergamot-training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cmake=3.21.1
  - pip=21.2.2
  - pip:
    - sacrebleu==2.0.0
    - mtdata==0.4.0
    - fasttext==0.9.2
    - regex==2019.8.19
    - sacremoses==0.1.0
    - langcodes==3.3.0
    - opusfilter==3.0.0rc2
    - git+https://github.com/hplt-project/opustrainer.git#egg=opustrainer
    - unbabel-comet=2.2.2
