####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###

experiment:
  dirname: lumi
  name: fiu-eng
  langpairs:
    - et-en
    - fi-en
    - liv-en

  #URL to the OPUS-MT model to use as the teacher
  opusmt-teacher: "https://object.pouta.csc.fi/Tatoeba-MT-models/fiu-eng/opus4m-2020-08-12.zip"
  
  # Specify if the teacher and the student are many2one
  one2many-teacher: False
  one2many-student: False

  #URL to the OPUS-MT model to use as the backward model
  opusmt-backward: "https://object.pouta.csc.fi/Tatoeba-MT-models/eng-fiu/opus2m-2020-08-01.zip"
  one2many-backward: True

  teacher-ensemble: 1
  
  split-length: 100000
  spm-vocab-size: 400 #Because we are dealing with very little data

  best-model: perplexity

  opusfilter:
    config: default #

datasets:
  train:
    #- tc_Tatoeba-Challenge-v2021-08-07
    - opus_ELRC_2922/v1
    - opus_liv4ever/v1
  devtest:
    - flores_dev
    - custom-corpus_/home/degibert/Documents/0_Work/multi-ftt/data/data/liv-en/wmt22
    #- tc_Tatoeba-Challenge-v2021-08-07
  test:
    - flores_devtest
    #- tc_Tatoeba-Challenge-v2021-08-07
    
  # train:
  #   tc_Tatoeba-Challenge-v2021-08-07: fi-en, et-en
  #   opus_liv4ever/v1: liv-en
  # devtest:
  #   flores_dev: fi-en, et-en
  #   generaltest22: liv-en
  # test:
  #   flores_dev: fi-en, et-en
  #   tc_Tatoeba-Challenge-v2021-08-07: liv-en
  #  train:
  #  - fi-en_tc_Tatoeba-Challenge-v2021-08-07
  #  - et-en_tc_Tatoeba-Challenge-v2021-08-07
  #  - liv-en_opus_liv4ever/v1
  #  devtest:
  #  - fi-en_flores_dev
  #  - et-en_flores_dev
  #  - liv-en_generaltest22
  #  test:
  #  - fi-en_flores_devtest
  #  - et-en_flores_devtest
  #  - liv-en_tc_Tatoeba-Challenge-v2021-08-07

#  corpus:
#    fi-en: opus_ELRC_2922/v1
#    et-en: opus_ELRC_2922/v1
#    liv-en: opus_liv4ever/v1
#  devset:
#    fi-en: flores_dev
#    et-en: flores_dev
#    liv-en: generaltest22
#  eval:
#    fi-en: flores_devtest
#    et-en: flores_devtest
#    liv-en: tc_Tatoeba-Challenge-v2021-08-07
  # - langpair: et-en
  #     train:
  #       - tc_Tatoeba-Challenge-v2021-08-07 
  #     devtest:
  #       - flores_dev
  #     test:
  #       - flores_devtest
  # - langpair: fi-en
  #     train:
  #       - tc_Tatoeba-Challenge-v2021-08-07 
  #     devtest:
  #       - flores_dev
  #     test:
  #       - flores_devtest
  # - langpair: en-es
  #     train:
  #       - opus_liv4ever/v1
  #     devtest:
  #       - flores_dev
  #     test:
  #       - generaltest22
