experiment:
  dirname: test
  name: fiu-eng_2
  langpairs:
    - et-en
    - fi-en

  #URL to the OPUS-MT model to use as the teacher
  opusmt-teacher: "https://object.pouta.csc.fi/Tatoeba-MT-models/fiu-eng/opus4m-2020-08-12.zip"

  #URL to the OPUS-MT model to use as the backward model
  opusmt-backward: "https://object.pouta.csc.fi/Tatoeba-MT-models/eng-fiu/opus2m-2020-08-01.zip"
  one2many-backward: True
  
  parallel-max-sentences: 1000
  split-length: 10000
  spm-sample-size: 400
  spm-vocab-size: 3000

  best-model: perplexity

marian-args:
  training-student:
    disp-freq: 10
    save-freq: 100
    valid-freq: 100
    after: 500u
  training-student-finetuned:
    disp-freq: 10
    save-freq: 100
    valid-freq: 100
    after: 500u

datasets:
  train:
    - opus_ELRC_2923__v1
  devtest:
    - flores_dev
  test:
    - flores_devtest