####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###

experiment:
  dirname: en-et
  name: en-et
  langpairs:
    - en-et

  teacher-ensemble: 1

  #URL to the OPUS-MT model to use as the teacher
  opusmt-teacher: "https://object.pouta.csc.fi/Tatoeba-MT-models/eng-est/opusTCv20210807+bt_transformer-big_2022-03-13.zip"
  #URL to the OPUS-MT model to use as the backward model
  opusmt-backward: "https://object.pouta.csc.fi/Tatoeba-MT-models/fiu-eng/opus4m-2020-08-12.zip"
  
  # Specify if the teacher and the student are many2one
  one2many-teacher: False
  one2many-student: False

  parallel-max-sentences: 100000
  split-length: 10000
  spm-vocab-size: 400

  best-model: perplexity

datasets:
  train:
    - opus_ELRC_2922/v1
  devtest:
    - flores_dev
  test:
    - flores_devtest