####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###

experiment:
  dirname: eng-fiu
  name: mtm23
  src: en
  trg: fi
  langpairs:
    - en-fi
    - en-et

  #URL to the OPUS-MT model to use as the teacher
  opusmt-teacher: "https://object.pouta.csc.fi/Tatoeba-MT-models/eng-fiu/opus2m-2020-08-01.zip"
  #URL to the OPUS-MT model to use as the backward model
  opusmt-backward: "https://object.pouta.csc.fi/Tatoeba-MT-models/fiu-eng/opus4m-2020-08-12.zip"

  parallel-max-sentences: 100000
  split-length: 10000

  best-model: perplexity

datasets:
  train:
    - opus_ELRC_2922/v1
  devtest:
    - flores_dev
  test:
    - flores_devtest