####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###

experiment:
  dirname: hf
  name: t5
  langpairs:
    - en-de

  parallel-max-sentences: 1000
  split-length: 10000
  spm-sample-size: 400
  spm-vocab-size: 3000

  best-model: perplexity
  
  huggingface:
    modelname: "google-t5/t5-small"
    modelclass: "transformers.AutoModelForSeq2SeqLM"
    lang_tags:
      en: English
      de: German
    prompt: "Translate {src_lang} to {tgt_lang}: {source}"

datasets:
  train:
    - ELRC-3293-EUROPARL_covid__v1
  devtest:
    - flores_dev
  test:
    - flores_devtest