####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###

experiment:
  dirname: hf
  name: opus
  langpairs:
    - en-et

  split-length: 1000

  best-model: perplexity
  
  huggingface:
    modelname: "Helsinki-NLP/opus-mt-mul-en"
    modelclass: "transformers.AutoModelForSeq2SeqLM"

datasets:
  train:
    - opus_ELRC_2922__v1
  devtest:
    - flores_dev
  test:
    - flores_devtest