name: Deploy Docs & Publish to PyPi

on:
  push:
    branches:
      - multi-ftt  # Update with your main branch or tag filters

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r docs/requirements.txt
    - name: Build docs
      run:  sphinx-build docs docs/build
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4
      with:
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build
        CLEAN: true