name: Deploy docs
on:
  push:
    branches:
      - multi-ftt # needs to be updated
    tags:
      - '*'
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    needs: [build-n-test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies to build docs
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install .[docs]
      - name: Build docs
        run: |
          sphinx-build docs docs/build
      - name: Deploy docs
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/build
          clean: true