name: Deploy docs on GitHub Pages

on:
  push:
    branches:
      - multi-ftt  # Update with your main branch or tag filters

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install sphinx
          if [ -f docs/requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build docs with Sphinx
        run: |
          sphinx-build -b html docs/ docs/build
          touch docs/build/.nojekyll  # Disable Jekyll processin
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/multi-ftt'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/build
          clean: true